config/routes.rb
Rails.application.routes.draw do

  post 'tweets/like/:tweet_id', to: 'likes#like', as: :like
  delete 'tweets/like/:tweet_id', to: 'likes#unlike', as: :unlike
  resources :tweets do
    resources :comments
  end

  resources :users do
    get 'tweets', to: 'users#tweets'
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  root to: 'tweets#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'email_validator/:email', to: 'users#email_validator'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    comment = Comment.find(params[:id])
    comment.destroy

    redirect_to comment.tweet
  end

  def edit
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @comment = Comment.find(params[:id])
    @tweet = @comment.tweet
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @comment.tweet
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
  
<div class="column is-6 is-offset-3">
  <div class="content is-size-3">
    <article class="media is-size-6">
      <div class="media-content">
        <div class="content">
          <p>
            <strong><%= comment.user.name %></strong> <small><%= time_ago_in_words(comment.created_at) %> ago </small>
          </p>
          <p>
            <%= comment.body %>
          </p>
        </div>
        <% if equal_with_current_user?(comment.user) %>
          <nav class="level is-mobile">
            <div class="level-left">
              <%= link_to edit_tweet_comment_path(comment.tweet, comment), class:"level-item" do %>
                <span class="icon is-small"><i class="fas fa-edit"></i></span>
              <% end %>
              <%= link_to tweet_comment_path(comment.tweet, comment), class:"level-item", method: :delete, data: { confirm: "Are you sure?"} do %>
                <span class="icon is-small"><i class="far fa-trash-alt"></i></span>
              <% end  %>
            </div>
          </nav>
        <% end %>
      </div>
    </article>
  </div>
</div>

app/views/comments/_form.html.erb
<article class="media">
  <div class="media-content">
    <%= form_with model: [tweet, comment], local: true do |form|  %>
      <div class="field">
        <p class="control">
          <%= form.text_field :body, class: "textarea", placeholder: "Your comment here!" %>
          <% if comment.errors.any? %>
            <% comment.errors.full_messages_for(:body).each do |msg| %>
              <p class="help is-danger"><%= msg %></p>
            <% end %>
          <% end %>
        </p>
      </div>
      <nav class="level">
        <div class="level-right">
          <%= form.submit submit, class: "button is-success is-info" %>
          <%= link_to 'Cancel', tweet_path(tweet), class: "button is-light" %>
        <% end %>
      </div>
    </div>
  </nav>
</div>
</article>

app/views/comments/edit.html.erb
<%= render 'form', tweet: @tweet, comment: @comment %>

app/views/comments/new.html.erb
<div class="columns is-multiline">
  <div class="column is-half is-offset-one-quarter">
    <section class="hero is-primary">
      <div class="hero-body has-text-centered">
        <div class="container">
          <h1 class="title">
            New Comment for:
            <strong class="is-italic"><%= @tweet.title %> tweet</strong>
          </h1>
        </div>
      </div>
    </section>
    <%= render 'form', tweet: @tweet, comment: @comment, submit: "New Comment" %>
  </div>
</div>