config/routes.rb
Rails.application.routes.draw do

  post 'tweets/like/:tweet_id', to: 'likes#like', as: :like
  delete 'tweets/like/:tweet_id', to: 'likes#unlike', as: :unlike
  resources :tweets do
    resources :comments
  end

  resources :users do
    get 'tweets', to: 'users#tweets'
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  root to: 'tweets#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'email_validator/:email', to: 'users#email_validator'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    @comment = Comment.new
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.order(created_at: :desc)
  end

  def new
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    if @tweet.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def edit
    session_notice(:danger, 'You must be logged in!') unless logged_in?
    @tweet = Tweet.find(params[:id])
    session_notice(:danger, 'Wrong user!') unless equal_with_current_user?(@tweet.user)
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    tweet = Tweet.find(params[:id])

    if logged_in?
      tweet.destroy
      redirect_to tweets_path
    else
      session_notice(:danger, 'Wrong user!')
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :body)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<div class="columns is-half is-offset-one-quarter">
  <div class="column is-half is-offset-one-quarter">
    <%= form_with model: tweet, local: true do |form| %>
      <%= form.label :title, class:"label" %>
      <%= form.text_field :title, class:"input is-rounded", placeholder: "Place your title here"%>
      <% if tweet.errors.any? %>
        <% tweet.errors.full_messages_for(:title).each do |msg| %>
          <p class="help is-danger"><%= msg %></p>
        <% end %>
      <% end%>
      <p>
        <%= form.label :body, class:"label" %>
        <%= form.text_area :body, class:"textarea", placeholder: "Place your text here" %>
      </p>
      <p>
        <%= form.submit submit, class: "button is-success is-info" %>
        <button class="button is-link is-outlined is-info"><%= link_to 'Cancel', root_path %></button>
      </p>
    <% end %>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="content">
  <div class="card">
    <header class="card-header">
      <p class="card-header-title title">
        <strong><%= @tweet.title %></strong>
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        <%= @tweet.body %>
      </div>
      <footer class="card-footer">
        <span>
          <i class="fas fa-clock"></i>
          <%= @tweet.created_at.strftime("%d %b %Y, %H:%M") %>
        </span>
      </footer>
      <br>
      <div class="buttons">
        <button class="button is-success is-info"><%= link_to 'OK', tweets_path %></button>
        <% if logged_in? && equal_with_current_user?(tweet.user) %>
          <button class="button is-link"><%= link_to 'Edit', edit_tweet_path %></button>
          <button class="button is-danger"><%= link_to 'Delete', tweet_path, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        <% end %>
        <% if logged_in? %>
          <button class="button is-light"><%= link_to 'New Comment', new_tweet_comment_path(@tweet) %></button>
        <% end %>
      </div>
      <div>
        <% if logged_in? && current_user.likes?(@tweet) %>
          <%= link_to unlike_path(@tweet), method: :delete, remote: true do %>
            <i class="fas red fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to like_path(@tweet), method: :post, remote: true do %>
            <i class="far blank fa-heart"></i>
          <% end %>
        <% end %>
        <%= @tweet.likes.count %>
        <% @tweet.likes.each do |l| %>
          <ul><%= l.user.name %></ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <h1 class="title">
      Edit tweet!
    </h1>
  </div>
</section>
<%= render 'form', tweet: @tweet, submit: 'Save Changes'  %>

app/views/tweets/index.html.erb
<div class="columns is-centered">
  <div class="column is-6">
    <div class="box content">
      <% @tweets.each do |tweet| %>
        <article class="post">
          <p> <small>Posted by: <%= tweet.user.name %> | <%= time_ago_in_words(tweet.created_at) %> ago</small></p>
          <div class="media">
            <div class="media-left">
              <p class="image is-32x32">
                <% if tweet.user.profile_picture.present? %>
                  <%= link_to image_tag(tweet.user.profile_picture, class:"image"), user_path(tweet.user) %>
                <% end %>
              </p>
            </div>
            <div class="media-content">
              <div class="content">
                <h2><%= link_to tweet.title, tweet_path(tweet) %></h2>
              </div>
            </div>
            <div class="media-right">
              <span class="has-text-grey-light"><i class="fas fa-comments"></i> <%= tweet.comments.count %></span>
            </div>
          </div>
        </article>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<section class="hero is-primary">
  <div class="hero-body">
    <h1 class="title">
      Create new tweet!
    </h1>
  </div>
</section>
<%= render 'form', tweet: @tweet, submit: 'Save Tweet'  %>

app/views/tweets/show.html.erb
<div class="columns is-multiline">
  <div class="column is-6 is-offset-3">
    <% if @comments.count > 3  %>
      <article class="message is-small is-danger has-text-centered">
        <div class="message-body">
          <strong>🔥🔥🔥 This tweet is very popular 🔥🔥🔥</strong>
        </div>
      </article>
    <% end %>
    <%= render @tweet %>
    <h3 class="subtitle is-4">Comments:</h3>
    <%= render @comments %>
  </div>
</div>