config/routes.rb
Rails.application.routes.draw do

  post 'tweets/like/:tweet_id', to: 'likes#like', as: :like
  delete 'tweets/like/:tweet_id', to: 'likes#unlike', as: :unlike
  resources :tweets do
    resources :comments
  end

  resources :users do
    get 'tweets', to: 'users#tweets'
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  root to: 'tweets#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'email_validator/:email', to: 'users#email_validator'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  has_secure_password

  has_many :comments, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :profile_picture


  before_save :email_to_downcase

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, length: { minimum: 6 }

  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session_notice(:warning, 'Already logged in') if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @conversation = Conversation.where(sender_id: current_user, receiver_id: @user).first_or_create


  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def tweets
    @user = User.find(params[:user_id])
  end

  def email_validator
    if params[:email].size <= 2
      render json: { valid: false }
    elsif User.find_by_email(params[:email])
      render json: { valid: false }
    else
      render json: { valid: true }
    end
  end

  private

  def user_params
    params.require(:user)
          .permit(:name, :email, :password, :password_confirmation, :profile_picture)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<section class="hero is-success is-fullheight">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="column is-4 is-offset-4">
        <h3 class="title has-text-black"><%= title %></h3>
        <hr class="login-hr">
        <p class="subtitle has-text-black"><%= subtitle %></p>
        <div class="box">
          <figure class="avatar">
            <% if @user.profile_picture.present? %>
              <%= image_tag @user.profile_picture %>
            <% else %>
              <%= image_tag 'https://placehold.it/128x128' %>
            <% end %>
          </figure>
          <%= form_with model: @user, local: true do |form| %>
            <div class='field'>
              <%= form.label :name, class:"label" %>
              <div class='control has-icons-left'>
                <%= form.text_field :name, class:"input", placeholder: "Your name here!"%>
                <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
                <% if @user.errors.any? %>
                  <% @user.errors.full_messages_for(:name).each do |msg| %>
                    <p class="help is-danger"><%= msg %></p>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class='field'>
              <%= form.label :email, class:"label" %>
              <div class='control has-icons-left' >
                <%= form.email_field :email, class:"input", placeholder: "Email" %>
                <span class="icon is-small is-left"><i class="fas fa-envelope"></i></span>
                  <span.username-icon-styles>
                  <span id="valid-username" class="fa fa-check-circle"></span>
                  <span id="invalid-username" class="fa fa-times-circle"></span>
                  </span>
                <% if @user.errors.any? %>
                  <% @user.errors.full_messages_for(:email).each do |msg| %>
                    <p class="help is-danger"><%= msg %></p>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class='field'>
              <%= form.label :profile_picture, class:"label" %>
              <%= form.file_field :profile_picture, class:"file-label" %>
            </div>
            <div class='field'>
              <%= form.label :password, class:"label" %>
              <div class='control has-icons-left'>
                <%= form.password_field :password, class:"input", placeholder: "Password" %>
                <span class="icon is-small is-left"><i class="fas fa-lock"></i></span>
                <% if @user.errors.any? %>
                  <% @user.errors.full_messages_for(:password).each do |msg| %>
                    <p class="help is-danger"><%= msg %></p>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class='field'>
              <%= form.label :password_confirmation, class:"label" %>
              <div class='control'>
                <%= form.password_field :password_confirmation, class:"input", placeholder: "Confirm password" %>
                <% if @user.errors.any? %>
                  <% @user.errors.full_messages_for(:password_confirmation).each do |msg| %>
                    <p class="help is-danger"><%= msg %></p>
                  <% end %>
                <% end %>
                <div class='buttons mt-3'>
                  <%= form.submit submit, class: "button is-info" %>
                  <button class="button is-link is-outlined is-info"><%= link_to 'Cancel', root_path %></button>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </section>

app/views/users/edit.html.erb
<%= render 'form', title: 'Edit profile', subtitle: 'Change your profile information', submit: 'Update Profile' %>

app/views/users/new.html.erb
<%= render 'form', title: 'New User', subtitle: 'Please fill up the registration!', submit: 'Create Account' %>



<script>
  console.log('Hello')
(document).ready(function() {
    $('#invalid-email').hide();
    $('#valid-email').hide();
    $('#user_email').on('keyup', function(event) {
      $.ajax({
        url: '/email_validator/' + $('#user_email').val(),
        type: 'GET',
        dataType: 'json',
        error: function(jqXHR, textStatus, errorThrown) {},
        success: function(data, textStatus, jqXHR) {
          if (data.valid === true) {
            $('#invalid-email').hide();
            return $('#valid-email').show();
          } else if (data.valid === false) {
            $('#valid-email').hide();
            return $('#invalid-email').show();
          }
        }
      });
      event.stopImmediatePropagation();
      return false;
    });
    return false;
  };


}).call(this);

</script>

app/views/users/show.html.erb
<div class="columns is-multiline">
  <div class="column is-half is-offset-one-quarter">
    <section class="hero is-primary">
      <div class="hero-body has-text-centered">
        <div class="container">
          <h1 class="title">
              <% if @user.profile_picture.present? %>
            <p>
            <%= image_tag @user.profile_picture, class: "profile-image" %>
            <% end %>
            </p>
            <strong> <%= @user.name %></strong>
          </h1>
            <% unless current_user == @user  %>
              <%= link_to conversation_messages_path(@conversation) do %>
               <span> Send message <i class="fas fa-envelope"></i> </span>
              <% end %>
            <% end %>
          <p><%= @user.email %></p>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/users/tweets.html.erb
<div class="columns is-centered">
  <div class="column is-6">
    <div class="box content">
      <% @user.tweets.each do |tweet| %>
      <article class="post">
       <p> <small>Posted by: <%= tweet.user.name %> | <%= time_ago_in_words(tweet.created_at) %> ago</small></p>
        <div class="media">
          <div class="media-left">
            <p class="image is-32x32">
              <% if tweet.user.profile_picture.present? %>
                <%= link_to image_tag(tweet.user.profile_picture, class:"image"), user_path(tweet.user) %>
              <% end %>
            </p>
          </div>
          <div class="media-content">
            <div class="content">
                    <h2><%= link_to tweet.title, tweet_path(tweet) %></h2>
            </div>
          </div>
          <div class="media-right">
            <span class="has-text-grey-light"><i class="fas fa-comments"></i> <%= tweet.comments.count %></span>
          </div>
        </div>
      </article>
      <% end %>
    </div>
  </div>
</div>