config/routes.rb
Rails.application.routes.draw do

  post 'tweets/like/:tweet_id', to: 'likes#like', as: :like
  delete 'tweets/like/:tweet_id', to: 'likes#unlike', as: :unlike
  resources :tweets do
    resources :comments
  end

  resources :users do
    get 'tweets', to: 'users#tweets'
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  root to: 'tweets#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'email_validator/:email', to: 'users#email_validator'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :body, presence: true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, scope: :receiver_id

  scope :between, lambda { |sender_id, receiver_id|
    where('(conversations.sender_id = ? AND conversations.receiver_id = ?) OR
    (conversations.receiver_id = ? AND conversations.sender_id = ?)',
          sender_id,
          receiver_id,
          sender_id,
          receiver_id)
  }

  def recipient(current_user)
    sender_id == current_user.id ? receiver : sender
  end

  def unread_message_count(current_user)
    messages.where('user_id != ? AND read = ?', current_user.id, false).count
  end
end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :tweet
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id


  def message_time
    created_at.strftime('%d/%m/%y at %l:%M %p')
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  has_secure_password

  has_many :comments, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :profile_picture


  before_save :email_to_downcase

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, length: { minimum: 6 }

  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = @tweet.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    comment = Comment.find(params[:id])
    comment.destroy

    redirect_to comment.tweet
  end

  def edit
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @comment = Comment.find(params[:id])
    @tweet = @comment.tweet
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @comment.tweet
    else
      render :edit
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like
    @tweet = Tweet.find(params[:tweet_id])
    redirect_to @tweet if @tweet.likes.find_or_create_by(user_id: current_user.id)
  end

  def unlike
    @tweet = Tweet.find(params[:tweet_id])
    redirect_to @tweet if @tweet.likes.where(user_id: current_user.id).destroy_all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages

    @messages.where("user_id != ? AND read = ?", current_user.id, false).update_all(read: true)

    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.user = current_user

    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
    @comment = Comment.new
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments.order(created_at: :desc)
  end

  def new
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    if @tweet.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def edit
    session_notice(:danger, 'You must be logged in!') unless logged_in?
    @tweet = Tweet.find(params[:id])
    session_notice(:danger, 'Wrong user!') unless equal_with_current_user?(@tweet.user)
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render :edit
    end
  end

  def destroy
    session_notice(:danger, 'You must be logged in!') unless logged_in?

    tweet = Tweet.find(params[:id])

    if logged_in?
      tweet.destroy
      redirect_to tweets_path
    else
      session_notice(:danger, 'Wrong user!')
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    session_notice(:warning, 'Already logged in') if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @conversation = Conversation.where(sender_id: current_user, receiver_id: @user).first_or_create


  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def tweets
    @user = User.find(params[:user_id])
  end

  def email_validator
    if params[:email].size <= 2
      render json: { valid: false }
    elsif User.find_by_email(params[:email])
      render json: { valid: false }
    else
      render json: { valid: true }
    end
  end

  private

  def user_params
    params.require(:user)
          .permit(:name, :email, :password, :password_confirmation, :profile_picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def session_notice(type, message)
    flash[type.to_sym] = message
    redirect_to root_path and return
  end

  def equal_with_current_user?(other_user)
    current_user == other_user
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <section class="container">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flash' %>
      <%= yield %>
    </section>
  </body>

app/views/shared/_flash.html.erb
    
<div class="columns is-half is-offset-one-quarter">
  <div class="column is-half is-offset-one-quarter">
    <% flash.each do |name, msg| %>
      <div class="notification is-<%= name %> has-text-centered">
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_modal.html.erb
  
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Delete</h4>
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
      <!-- Modal body -->
      <div class="modal-body">
        Are you sure you want to delete?
      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
        <% if logged_in? && equal_with_current_user?(@tweet.user) %>
          <button type="button" class="button is-danger" data-dismiss="modal"><%= link_to "Yes", tweet_path, method: :delete %></button>
          <button type="button" class="button is-success is-info" data-dismiss="modal">No</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="container">
    <div class="navbar-brand">
      <%= link_to (image_tag 'https://twiitermk.s3.eu-central-1.amazonaws.com/logo1.png', size: "230x350", class:"navbar-item"), root_path %>
      <span class="navbar-burger burger" data-target="navbarMenu">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navbarMenu" class="navbar-menu">
      <div class="navbar-end">
        <% if logged_in? %>
          <%= link_to new_tweet_path do %>
            <button class="button navbar-item">New tweet<span class="icon is-small ml-1 mr-1"><i class="fa fa-plus-circle" aria-hidden="true"></i></span></button>
          <% end %>
          <div class="navbar-item has-dropdown is-hoverable myprofile">
            <%= link_to user_path(current_user) do %>
              <div class="navbar-link white"><%= current_user.name %><span class="icon is-small ml-1"><i class="fa fa-user" aria-hidden="true"></i></span></div>
            <% end %>
            <div class="navbar-dropdown">
              <%= link_to user_tweets_path(current_user), class:"navbar-item" do %>
                My tweets <span class="tag is-success is-light ml-1"><%= current_user.tweets.count %></span>
              <% end %>
              <%= link_to conversations_path(current_user), class:"navbar-item" do %>
                Messages
              <% end %>
              <%= link_to user_path(current_user), class:"navbar-item" do %>
                My Profile
                <% if current_user.profile_picture.present?  %>
                  <%= image_tag current_user.profile_picture, class:"i round ml-1" %>
                <% end %>
              <% end %>
              <%= link_to edit_user_path(current_user), class:"navbar-item" do %>
                Edit Profile<span class="icon is-small has-text-info ml-1"><i class="fa fa-cog" aria-hidden="true"></i></span>
              <% end %>
              <hr class="navbar-divider">
              <%= link_to logout_path, method: :delete, class:"navbar-item" do %>
                Logout <span class="icon is-small has-text-danger ml-1"><i class="fa fa-window-close" aria-hidden="true"></i></span>
              <% end %>
            <% else %>
              <div class="navbar-item">
                <div class="buttons">
                  <button class="button is-primary is-inverted"><%= link_to 'Login', login_path %></button>
                  <button class="button is-primary is-inverted"><%= link_to 'Sign Up', new_user_path %></button>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <script>
      (function() {
          var burger = document.querySelector('.burger');
          var menu = document.querySelector('#'+burger.dataset.target);
          burger.addEventListener('click', function() {
              burger.classList.toggle('is-active');
              menu.classList.toggle('is-active');
          });
      })();
    </script>